# Generated by Django 3.2.11 on 2022-02-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='NULL', upload_to='images'),
        ),
    ]
